site_name: Data Structure and Algorithms

extra_javascript:
  - mathjax-config.js
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/3.2.0/es5/tex-mml-chtml.js

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - codehilite:
      linenums: false
      guess_lang: false
      use_pygments: true
      noclasses: true
      pygments_style: manni

theme:
  name: 'material'
  highlightjs: true
  hljs_languages: [python]
  include_homepage_in_sidebar: true
  prev_next_buttons_location: bottom
  navigation_depth: 4
  titles_only: false
  sticky_navigation: true
  collapse_navigation: true

extra_css:
  - extra.css

extra:
  analytics:
    provider: google
    property: UA-156178967-1



nav:
- Home: index.md
- Introduction: introduction.md
- Lists: lists.md
- Tuples: tuples.md
- Sets: sets.md
- Dictionaries: dictionaries.md
- Strings: strings.md
- Linked Lists: linked_lists.md
- Stacks: stacks.md
- Queues: queues.md
- Priority Queues: priority_queues.md
- Heaps: heaps.md
- Hash Tables: hash_tables.md
- Trees: trees.md
- Graphs: graphs.md
- Algorithm Analysis: algorithm_analysis.md
- Recursion: recursion.md
- Sorting Algorithms: sorting_algorithms.md
- Searching Algorithms: searching_algorithms.md
- Divide and Conquer: divide_and_conquer.md
- Dynamic Programming: dynamic_programming.md
- Greedy Algorithms: greedy_algorithms.md
- Backtracking: backtracking.md
- Branch and Bound: branch_and_bound.md
- Depth-First Search: depth_first_search.md
- Breadth-First Search: breadth_first_search.md
- Dijkstra's Algorithm: dijkstras_algorithm.md
- Bellman-Ford Algorithm: bellman_ford_algorithm.md
- A* Algorithm: a_star_algorithm.md
- Kruskal's Algorithm: kruskals_algorithm.md
- Prim's Algorithm: prims_algorithm.md
- Floyd-Warshall Algorithm: floyd_warshall_algorithm.md
- Topological Sort: topological_sort.md
- Tries: tries.md
- Segment Trees: segment_trees.md
- Fenwick Trees: fenwick_trees.md
- Suffix Arrays and Trees: suffix_arrays_and_trees.md
- Bloom Filters: bloom_filters.md
- Union-Find: union_find.md
- Memoization: memoization.md
- Time Complexity: time_complexity.md
- Space Complexity: space_complexity.md
- Amortized Analysis: amortized_analysis.md
- MapReduce: mapreduce.md

